services:
  urlshare:
    image: urlshare
    container_name: urlshare
    ports:
      - "10000:10000"
    environment:
      - USERNAME=user
      - PASSWORD_SHA256_HASH=5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
